services: docker
before_install:
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t "${DOCKER_REPO}:${TRAVIS_TAG}" .
deploy:
  provider: script
  api_key: "$GITHUB_API_TOKEN"
  script: docker push "${DOCKER_REPO}:${TRAVIS_TAG}"
  skip_cleanup: false
  on:
    tags: true